name = "app2001"
description = "RHEL8, python, oscap"
version = "0.0.3"
modules = []
groups = []

[[packages]]
name = "insights-client"
version = "*"

[[packages]]
name = "openscap-scanner"
version = "*"

[[packages]]
name = "openssh"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "platform-python"
version = "*"

[[packages]]
name = "scap-security-guide"
version = "*"

[customizations]

[[customizations.user]]
name = "rheldemo"
description = "Red Hat Nordics"
password = "$6$qgtDGzzlmyqGnCOB$FA58kD2VZ1lmPB3rYib7jtH0a5tByi2Kwqp29Zw7rySqV.jnMAK9qbWUZ.OsDvO/jljWActCC9pmBiXBRZdAa/"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNB373dBFtduPYMW6ivq+8toN22kTs+E/CZlJlBARY8NieYMizEDiIzfPcKAq/IzXnpoR4tnjfI08Tz3kNKNo0sfE5hCD4BtBWo+FdXpnX1EF4gMAFGbeEMEO3wf9VtN+iLMFhW98Jz7dV104SI/vrzJBZllta5kRXIzr4YAHW2RGDHQ5sWdFSeAv0afk5MrbqrNcQ2fKeAFuS5hsP9hBNpCA8SNCFCbR9UbxMjp6Q7BUGWi1kh4oVFS0TOAxOIZPbcRYNYfOixfK85S4w1GaZ2GCMs/NbQ/s6jLO7zSESdSVQeufMX1sd7K7xbaH1khD33NI1P7bG2isPYUkS0++r root@rhel8demo.rhnerdics.local"
home = "/home/rhdemo/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]

[customizations.services]
enabled = ["sshd", "cockpit.socket", "httpd"]
disabled = ["postfix", "telnetd"]
